### ISSUE TITLE
Up bimozie zip file

### ISSUE THREAD

**Issue by sviet2k** [billythekids/kodi.repository#1]
Can you please update the version of the zip file to make repo updating the latest one?
Thank you

**Comment by billythekids** [comment]
i dont know how to do it :|

**Comment by sviet2k** [comment]
I guess you just download the zip file from plugin.video.bimozie (or build the zip file from your souce code in PC) and upload this zip into:
kodi.repository.zips.plugin.video.bimozie with the correct plugin version then the bimozie plugin will be updated automatically via your  bimozie repo. :)

**Comment by billythekids** [comment]
Do you know how to solve dependence issue? So i'm able to manage all depending package as needed

**Comment by billythekids** [comment]
Done 💃
